BootstrapBlazor/BootstrapBlazor.Extensions

- src/components/BootstrapBlazor.Sortable/BootstrapBlazor.Sortable.csproj
- src/components/BootstrapBlazor.Sortable/Components/SortableList.razor.js
missing item when set Clone to true
close #1
> fix(Sortable): missing item when set Clone to true

- src/components/BootstrapBlazor.DockView/BootstrapBlazor.DockView.csproj
- src/components/BootstrapBlazor.DockView/Components/DockViewConfig.cs
{Detail}
Fixes #9 
{Justification}
> fix(DockView): IsLock parameter not work

- src/components/BootstrapBlazor.FileViewer/BootstrapBlazor.FileViewer.csproj
- src/components/BootstrapBlazor.FileViewer/FileViewer.razor
- src/components/BootstrapBlazor.FileViewer/FileViewer.razor.cs
> chore(FileViewer): bump version 8.1.0

- src/components/BootstrapBlazor.DockView/BootstrapBlazor.DockView.csproj
- src/components/BootstrapBlazor.DockView/Components/DockViewV2.razor
- src/components/BootstrapBlazor.DockView/Components/DockViewV2.razor.cs
{Detail}
Fixes #15 
{Justification}
> feat(DockView): update InvokeInit method

- .github/pull_request_template.md
- .github/workflows/auto-pull-request-checks.yml
> chore(PullRequest): update pull request template

- src/components/BootstrapBlazor.Topology/BootstrapBlazor.Topology.csproj
- src/components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.cs
- src/components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.css
> feat(Topology): remove css isoloation

- src/components/BootstrapBlazor.BaiduOcr/BootstrapBlazor.BaiduOcr.csproj
> feat(BaiduOrc): update dependence

- src/components/BootstrapBlazor.OCR/AiForm.razor.cs
- src/components/BootstrapBlazor.OCR/AiFormDocumentEmnu.cs
- src/components/BootstrapBlazor.OCR/AzureOpenAI.razor.cs
- src/components/BootstrapBlazor.OCR/AzureSTS.razor.cs
- src/components/BootstrapBlazor.OCR/BootstrapBlazor.OCR.csproj
- src/components/BootstrapBlazor.OCR/Directory.Build.props
- src/components/BootstrapBlazor.OCR/EnumAzureOpenAIModel.cs
- src/components/BootstrapBlazor.OCR/EnumVoiceName.cs
- src/components/BootstrapBlazor.OCR/OCR.razor.cs
- src/components/BootstrapBlazor.OCR/PlayAudio.razor.cs
- src/components/BootstrapBlazor.OCR/Services/AiFormService.cs
- src/components/BootstrapBlazor.OCR/Services/AiFormServiceCollectionExtensions.cs
- src/components/BootstrapBlazor.OCR/Services/BaseService.cs
- src/components/BootstrapBlazor.OCR/Services/OcrService.cs
- src/components/BootstrapBlazor.OCR/Services/OcrServiceAdv.cs
- src/components/BootstrapBlazor.OCR/Services/OcrServiceCollectionExtensions.cs
- src/components/BootstrapBlazor.OCR/Services/OpenAIClientService.cs
- src/components/BootstrapBlazor.OCR/Services/StsService.cs
- src/components/BootstrapBlazor.OCR/Services/TranslateService.cs
- src/components/BootstrapBlazor.OCR/Translate.razor.cs
- src/components/BootstrapBlazor.OCR/Utils/Utils.cs
> refactor(OCR): bump version 8.1.0

- src/components/BootstrapBlazor.FileViewer/BootstrapBlazor.FileViewer.csproj
> chore(FileViewer): bump version 8.1.1

- src/components/BootstrapBlazor.Html2Pdf/BootstrapBlazor.Html2Pdf.csproj
> feat(Html2Pdf): bump version 8.2.1

- src/Directory.Build.props
- src/Frameworks.props
- src/components/BootstrapBlazor.AntDesignIcon/BootstrapBlazor.AntDesignIcon.csproj
> chore(AntDesignIcon): bump version 8.1.0

- src/components/BootstrapBlazor.CodeEditor/BootstrapBlazor.CodeEditor.csproj
- src/components/BootstrapBlazor.CodeEditor/Components/CodeEditor/CodeEditor.razor.js
> chore(CodeEditor): bump version 8.1.0

- src/components/BootstrapBlazor.CodeEditor/BootstrapBlazor.CodeEditor.csproj
- src/components/BootstrapBlazor.CodeEditor/Components/CodeEditor/CodeEditor.razor.js
> chore(CodeEditor): bump version 8.1.1

- src/components/BootstrapBlazor.Dock/BootstrapBlazor.Dock.csproj
> chore(Dock): bump version 8.2.0

- src/components/BootstrapBlazor.AzureOpenAI/BootstrapBlazor.AzureOpenAI.csproj
- src/components/BootstrapBlazor.AzureOpenAI/Services/AzureOpenAIChatMessage.cs
- src/components/BootstrapBlazor.AzureOpenAI/Services/AzureOpenAIService.cs
> chore(AzureOpenAI): bump version 8.1.0

- src/components/BootstrapBlazor.AzureSpeech/BootstrapBlazor.AzureSpeech.csproj
> chore(AzureSpeech): bump version 8.1.0

- src/components/BootstrapBlazor.AzureTranslator/BootstrapBlazor.AzureTranslator.csproj
> chore(AzureTranslator): bump version 8.1.1

- src/components/BootstrapBlazor.BaiduOcr/BootstrapBlazor.BaiduOcr.csproj
> chore(BaiduOcr): bump version 8.1.2

- src/components/BootstrapBlazor.BaiduSpeech/BootstrapBlazor.BaiduSpeech.csproj
- src/components/BootstrapBlazor.BaiduSpeech/Services/BaiduRecognizerProvider.cs
- src/components/BootstrapBlazor.SummerNote/BootstrapBlazor.SummerNote.csproj
> chore(SummerNote): bump version 8.1.0

- BootstrapBlazor.Extensions.sln
- src/components/BootstrapBlazor.Holiday/BootstrapBlazor.Holiday.csproj
- src/components/BootstrapBlazor.SummerNote/BootstrapBlazor.SummerNote.csproj
- test/Directory.Build.props
- test/UnitTestEditor/BootstrapBlazorTestBase.cs
- test/UnitTestEditor/EditorTest.cs
- test/UnitTestEditor/UnitTestEditor.csproj
- test/UnitTestHoliday/UnitTest1.cs
- test/UnitTestHoliday/UnitTestHoliday.csproj
> chore(Holiday): bump version 8.1.0

- src/components/BootstrapBlazor.BaiduSpeech/Services/BaiduRecognizerProvider.cs
- test/Directory.Build.props
> chore(BaiduSpeech): bump version 8.1.1

- src/components/BootstrapBlazor.BootstrapIcon.Extensions/BootstrapBlazor.BootstrapIcon.Extensions.csproj
> chore(BootstrapIcon): bump version 8.1.0

- src/components/BootstrapBlazor.DockView/BootstrapBlazor.DockView.csproj
> chore(Dockview): bump version 8.2.0

- src/extensions/BootstrapBlazor.DataAccess.SqlSugar/BootstrapBlazor.DataAccess.SqlSugar.csproj
> chore(SqlSugar): bump version 8.3.1

- src/extensions/BootstrapBlazor.DataAccess.PetaPoco/BootstrapBlazor.DataAccess.PetaPoco.csproj
> chore(PetaPoco): bump version 8.3.1

- src/extensions/BootstrapBlazor.DataAccess.EntityFrameworkCore/BootstrapBlazor.DataAccess.EntityFrameworkCore.csproj
> chore(EFCore): remove net5 support

- test/UnitTestEditor/BootstrapBlazorTestBase.cs
- test/UnitTestEditor/EditorTest.cs
> test(Editor): add bUnit namespace

- src/extensions/BootstrapBlazor.DataAccess.PetaPoco/BootstrapBlazor.DataAccess.PetaPoco.csproj
- src/extensions/BootstrapBlazor.DataAccess.PetaPoco/DatabaseExtensions.cs
> fix(PetaPoco): missing where keyword

- src/extensions/BootstrapBlazor.DataAccess.PetaPoco/BootstrapBlazor.DataAccess.PetaPoco.csproj
- src/extensions/BootstrapBlazor.DataAccess.PetaPoco/PetaPocoServiceCollectionExtensions.cs
> feat(PetaPoco): add AddPetaPoco extension method

- src/extensions/BootstrapBlazor.DataAccess.PetaPoco/BootstrapBlazor.DataAccess.PetaPoco.csproj
- src/extensions/BootstrapBlazor.DataAccess.PetaPoco/PetaPocoServiceCollectionExtensions.cs
> feat(PetaPoco): add IServiceProvider parameter

- src/components/BootstrapBlazor.BarcodeGenerator/BarcodeGeneratorOption.cs
- src/components/BootstrapBlazor.BarcodeGenerator/BootstrapBlazor.BarcodeGenerator.csproj
> chore(Generator): bump version 8.4.0

- src/components/BootstrapBlazor.ImageCropper/BootstrapBlazor.ImageCropper.csproj
- src/components/BootstrapBlazor.ImageCropper/ImageCropperOption.cs
> chore(ImageCropper): bump version 8.3.0

- src/components/BootstrapBlazor.Player/BootstrapBlazor.Player.csproj
- src/components/BootstrapBlazor.Player/PlayerMode.cs
- src/components/BootstrapBlazor.Player/PlayerSource.cs
> chore(Player): bump version 8.3.0

- src/components/BootstrapBlazor.DockView/BootstrapBlazor.DockView.csproj
- src/components/BootstrapBlazor.DockView/Components/DockViewContentType.cs
- src/components/BootstrapBlazor.DockView/Components/DockViewRenderMode.cs
> chore(DockView): bump version 8.4.0

- src/components/BootstrapBlazor.Topology/Components/Topology/Topology.razor.js
- src/components/BootstrapBlazor.Topology/wwwroot/fillLines.js
> feat(Topology): add IsDsiableAnchor parameter

- BootstrapBlazor.Extensions.sln
- src/components/BootstrapBlazor.SVGEditor/BootstrapBlazor.SvgEditor.csproj
> chore(SvgEditor): bump version 9.0.0-beta01

- src/components/BootstrapBlazor.WinBox/BootstrapBlazor.WinBox.csproj
- src/components/BootstrapBlazor.WinBox/wwwroot/css/winbox.bundle.css
> feat(WinBox): compatiable dark mode

- src/components/BootstrapBlazor.Markdown/BootstrapBlazor.Markdown.csproj
- src/components/BootstrapBlazor.Markdown/Components/Markdown/Markdown.razor.cs
> feat(Markdown): support default Language

- src/components/BootstrapBlazor.UniverSheet/BootstrapBlazor.UniverSheet.csproj
> chore(UniverSheet): bump version 9.0.4

- src/components/BootstrapBlazor.UniverSheet/BootstrapBlazor.UniverSheet.csproj
- src/components/BootstrapBlazor.UniverSheet/wwwroot/univer.js
> feat(UniverSheet): remove console log

- src/components/BootstrapBlazor.Vditor/Vditor.razor.cs
- src/components/BootstrapBlazor.Vditor/Vditor.razor.js
- src/components/BootstrapBlazor.Vditor/wwwroot/css/vditor.css
> feat(Vditor): support validate form

- src/components/BootstrapBlazor.CherryMarkdown/BootstrapBlazor.CherryMarkdown.csproj
- src/components/BootstrapBlazor.CherryMarkdown/Components/CherryMarkdown/CherryMarkdown.razor.js
> feat(CherryMarkdown): bump version 9.0.3
